sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    database: 11

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tD96dA3wzkm6AeASiGo
    access-key-secret: 9uoZx7WUPwqvVhW1bbHuihX5HekvuZ
    bucket-name: sky-itcast-zehuang