name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend CI (Java)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven deps
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('sky-server/**/pom.xml') }}
          restore-keys: |
            m2-

      - name: Build backend
        working-directory: backend
        run: mvn -B clean package
